# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160730_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nutritional_info',
            new_name='nutrition',
        ),
    ]
