# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160801_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='ingridients/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='ingridients',
            field=models.ManyToManyField(related_name='products', to='products.Ingridient'),
        ),
    ]
