# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.SmallIntegerField(choices=[(1, 'Radio'), (2, 'Checkbox'), (3, 'Dropdown')])),
                ('members', models.ManyToManyField(through='products.Membership', to='products.ProductOption')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductOptionGroup'),
        ),
        migrations.AddField(
            model_name='membership',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='products.ProductOption'),
        ),
    ]
