# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20160902_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='product_option',
            new_name='option',
        ),
    ]
