# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20160902_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoptiongroup',
            old_name='members',
            new_name='options',
        ),
    ]
