# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20160902_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptiongroup',
            name='options',
            field=models.ManyToManyField(related_name='groups', through='products.Membership', to='products.ProductOption'),
        ),
    ]
