# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20160902_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoptiongroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
