# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20160902_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
