# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_membership_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoptiongroup',
            name='products',
            field=models.ManyToManyField(related_name='groups', to='products.Product'),
        ),
    ]
